//------------------------------------------------------------------------
// Copyright(c) 2022 SBM.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"LatencySpy.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"LatencySpy VST3 (64Bit)"
#else
#define stringFileDescription	"LatencySpy VST3"
#endif
#define stringCompanyName		"SBM\0"
#define stringLegalCopyright	"Copyright(c) 2022 SBM."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
